# This file is part of the dune-ldg-ns project:
#   https://github.com/dune-gdt/dune-ldg-ns
# Copyright 2026 dune-ldg-ns developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   René Fritze (2026)

Module: dune-ldg-ns
Version: 0.1.0
Maintainer: rene+anthropic@fritze.me
Depends: dune-gdt
